### ISSUE TITLE
FLipMouse - Teensy Update Code

### ISSUE THREAD

**Issue by benjaminaigner** [asterics/Addon-Bluetooth-WebGUI#5]
And now the same example for the Teensy based FLipMouse:

https://github.com/benjaminaigner/halfkay-webusb

It is a little bit different, but due to the fact that there is WebHID as well, it was easier than the AVR109 uploader :+1:

**Comment by klues** [comment]
Thanks for your work 👍 
I've implemented the firmware update to the WebGUI, see https://flipmouse.asterics.eu/#tabGeneral
For testing purposes it's possible to enter `showUpgradeButton = true` to console before reopening tab "General" in order to be able to overwrite the firmware despite of being up-to-date.
