### ISSUE TITLE
update of release data

### ISSUE THREAD

**Issue by ChrisVeigl** [asterics/Addon-Bluetooth-WebGUI#9]
is there a way to get data from a new release (firmware files, settings files, setting descriptions) into the WebGUI without clearing the whole browser cache/cookies in the browser settings (which might be complicated for users) ?

multiple page reloads did not work.

it would be nice to have a button (e.g. in the genereal tab) like "get latest firmware and settings".

**Comment by klues** [comment]
Thanks for reporting!
Should be fixed with https://github.com/asterics/Addon-Bluetooth-WebGUI/commit/57541d669eb4c1e79cf1ff6f66829430bc7dab24

The problem was my manual caching which isn't needed anymore, since I'm now using the caches of ServiceWorkers.
Caching strategies are:
* [Stale-While-Revalidate](https://developers.google.com/web/tools/workbox/modules/workbox-strategies#stale-while-revalidate) for all files except API-calls. This means webGUI always works instantly also without internet connection, but code changes are only updated after 2x refresh (F5).
* [Network-First](https://developers.google.com/web/tools/workbox/modules/workbox-strategies#network_first_network_falling_back_to_cache) for all API-calls, meaning that all firmware and setting files always should be up-to-date with internet connection while also working without internet connection as a fallback.
